<script setup>
import { computed, reactive, ref } from 'vue'
import { CONTENT_FILES, clearConfig, commitContentFile, fetchContentFile, getSavedConfig, saveConfig } from '../composables/useGithubApi'
import { openMediaLibrary } from '../composables/useCloudinary'

const config = reactive(getSavedConfig())
const path = ref(CONTENT_FILES[0]); const content = ref(''); const sha = ref(''); const status = ref(''); const busy = ref(false)
const isDevelopment = import.meta.env.DEV
const useLocal = ref(isDevelopment)
const canUse = computed(() => config.token && config.repo)
async function load() { if (!useLocal.value && !canUse.value) return; busy.value = true; status.value = ''; try { if (useLocal.value) { const response = await fetch(`/__portfolio-admin/content?file=${encodeURIComponent(path.value)}`); if (!response.ok) throw new Error('本地内容接口不可用。请通过 npm run dev:admin 启动。'); content.value = JSON.stringify(await response.json(), null, 2); status.value = '已加载本地文件。' } else { saveConfig(config); const file = await fetchContentFile({ ...config, path: path.value }); content.value = JSON.stringify(file.content, null, 2); sha.value = file.sha; status.value = '已加载 GitHub 当前版本。' } } catch (error) { status.value = `加载失败：${error.message}` } finally { busy.value = false } }
async function save() { let parsed; try { parsed = JSON.parse(content.value) } catch { status.value = 'JSON 格式无效，请修正后再提交。'; return } busy.value = true; try { if (useLocal.value) { const response = await fetch(`/__portfolio-admin/content?file=${encodeURIComponent(path.value)}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(parsed) }); if (!response.ok) throw new Error('无法写入本地文件。'); status.value = '已写入本地 JSON，Vite 会自动刷新页面。' } else { await commitContentFile({ ...config, path: path.value, content: parsed, sha: sha.value }); await load(); status.value = '已创建 Git 提交，Cloudflare Pages 将自动部署。' } } catch (error) { status.value = `提交失败：${error.message}` } finally { busy.value = false } }
async function selectImage() { busy.value = true; try { const asset = await openMediaLibrary(); if (!asset) { status.value = '已关闭 Media Library，未选择图片。'; return } await navigator.clipboard.writeText(JSON.stringify(asset, null, 2)); status.value = '已从 Cloudinary Media Library 选择图片，资产对象已复制到剪贴板。' } catch (error) { status.value = error.message } finally { busy.value = false } }
function logout() { clearConfig(); config.token = ''; config.repo = ''; content.value = ''; sha.value = '' }
</script>

<template><main class="admin-page"><header><div><p class="eyebrow">Private content workspace</p><h1>Portfolio Admin</h1></div></header><aside><strong>{{ useLocal ? '本地开发模式：' : '安全边界：' }}</strong>{{ useLocal ? '修改会直接写入当前项目的 src/data JSON 文件；此接口只存在于 Vite 开发服务器。' : '此构建只能部署在受 Cloudflare Access（GitHub 身份）保护的独立 Admin 域名。Token 仅保存在当前浏览器会话，不会写入仓库。' }}</aside><div v-if="isDevelopment" class="mode-switch"><label><input v-model="useLocal" type="checkbox" /> 直接修改本地 JSON</label></div><section v-if="!useLocal" class="config"><label>GitHub Fine-grained Token<input v-model="config.token" type="password" placeholder="github_pat_…" /></label><label>Repository<input v-model="config.repo" placeholder="owner/repo" /></label><label>Branch<input v-model="config.branch" /></label><button :disabled="busy || !canUse" @click="load">{{ busy ? '处理中…' : '加载' }}</button><button class="secondary" @click="logout">清除会话</button></section><section v-else class="local-actions"><button :disabled="busy" @click="load">{{ busy ? '处理中…' : '加载本地文件' }}</button></section><p v-if="status" class="status">{{ status }}</p><section class="editor"><div class="editor-bar"><select v-model="path" @change="load"><option v-for="file in CONTENT_FILES" :key="file">{{ file }}</option></select><button class="upload" type="button" :disabled="busy" @click="selectImage">打开 Cloudinary 媒体库</button></div><textarea v-model="content" spellcheck="false" placeholder="加载后编辑 JSON 内容"></textarea><button class="commit" :disabled="busy || !content" @click="save">{{ useLocal ? '保存到本地 JSON' : 'Commit & Deploy' }}</button></section></main></template>

<style scoped>.admin-page{width:min(1100px,calc(100% - 48px));margin:0 auto;padding:60px 0;font-family:Manrope,"Noto Sans SC",sans-serif}.admin-page header{border-bottom:1px solid #d7d5cf;padding-bottom:22px}.admin-page h1{font-size:38px;letter-spacing:-.06em;margin:0}.admin-page aside{margin:22px 0;background:#fff1dc;padding:16px 18px;font-size:13px;line-height:1.6}.mode-switch{font-size:13px;margin:12px 0}.config{display:grid;grid-template-columns:2fr 1fr 100px auto auto;gap:12px;align-items:end}.config label{font-size:11px;font-weight:700;text-transform:uppercase;color:#727272}.config input,.editor select{display:block;width:100%;margin-top:6px;background:#fff;border:1px solid #d7d5cf;padding:11px;font:13px "DM Mono",monospace}.config button,.commit,.upload,.local-actions button{border:0;background:#1f2328;color:#fff;padding:12px 16px;font-weight:700;cursor:pointer}.config .secondary{background:#777}.local-actions{margin-bottom:12px}.status{font-size:13px}.editor{border:1px solid #d7d5cf;background:#fff}.editor-bar{display:flex;justify-content:space-between;gap:12px;padding:12px;border-bottom:1px solid #d7d5cf}.upload{background:#fff;color:#1f2328;border:1px solid #d7d5cf}.editor textarea{width:100%;height:540px;border:0;resize:vertical;padding:20px;font:13px/1.6 "DM Mono",monospace;outline:0}.commit{margin:12px;background:#ff5a36}@media(max-width:700px){.admin-page{width:calc(100% - 32px);padding-top:35px}.config{grid-template-columns:1fr}.editor textarea{height:400px}.editor-bar{align-items:flex-start;flex-direction:column}}</style>
