<script setup>
import { computed, reactive, ref } from 'vue'
import { CONTENT_FILES, clearConfig, commitContentFile, fetchContentFile, getSavedConfig, saveConfig } from '../composables/useGithubApi'
import { uploadImage } from '../composables/useCloudinary'

const config = reactive(getSavedConfig())
const path = ref(CONTENT_FILES[0]); const content = ref(''); const sha = ref(''); const status = ref(''); const busy = ref(false)
const canUse = computed(() => config.token && config.repo)
async function load() { if (!canUse.value) return; busy.value = true; status.value = ''; try { saveConfig(config); const file = await fetchContentFile({ ...config, path: path.value }); content.value = JSON.stringify(file.content, null, 2); sha.value = file.sha; status.value = '已加载当前版本。' } catch (error) { status.value = `加载失败：${error.message}` } finally { busy.value = false } }
async function save() { let parsed; try { parsed = JSON.parse(content.value) } catch { status.value = 'JSON 格式无效，请修正后再提交。'; return } busy.value = true; try { await commitContentFile({ ...config, path: path.value, content: parsed, sha: sha.value }); await load(); status.value = '已创建 Git 提交，Cloudflare Pages 将自动部署。' } catch (error) { status.value = `提交失败：${error.message}` } finally { busy.value = false } }
async function upload(event) { const file = event.target.files?.[0]; if (!file) return; busy.value = true; try { const asset = await uploadImage(file); await navigator.clipboard.writeText(JSON.stringify(asset, null, 2)); status.value = '图片已上传，资产对象已复制到剪贴板，可粘贴到项目的 cover/avatar 字段。' } catch (error) { status.value = error.message } finally { busy.value = false } }
function logout() { clearConfig(); config.token = ''; config.repo = ''; content.value = ''; sha.value = '' }
</script>

<template><main class="admin-page"><header><div><p class="eyebrow">Private content workspace</p><h1>Portfolio Admin</h1></div></header><aside><strong>安全边界：</strong>此构建只能部署在受 Cloudflare Access（GitHub 身份）保护的独立 Admin 域名。Token 仅保存在当前浏览器会话，不会写入仓库。</aside><section class="config"><label>GitHub Fine-grained Token<input v-model="config.token" type="password" placeholder="github_pat_…" /></label><label>Repository<input v-model="config.repo" placeholder="owner/repo" /></label><label>Branch<input v-model="config.branch" /></label><button :disabled="busy || !canUse" @click="load">{{ busy ? '处理中…' : '加载' }}</button><button class="secondary" @click="logout">清除会话</button></section><p v-if="status" class="status">{{ status }}</p><section class="editor"><div class="editor-bar"><select v-model="path" @change="load"><option v-for="file in CONTENT_FILES" :key="file">{{ file }}</option></select><label>上传图片<input type="file" accept="image/*" @change="upload" /></label></div><textarea v-model="content" spellcheck="false" placeholder="加载后编辑 JSON 内容"></textarea><button class="commit" :disabled="busy || !content" @click="save">Commit & Deploy</button></section></main></template>

<style scoped>.admin-page{width:min(1100px,calc(100% - 48px));margin:0 auto;padding:60px 0;font-family:Manrope,"Noto Sans SC",sans-serif}.admin-page header{border-bottom:1px solid #d7d5cf;padding-bottom:22px}.admin-page h1{font-size:38px;letter-spacing:-.06em;margin:0}.admin-page aside{margin:22px 0;background:#fff1dc;padding:16px 18px;font-size:13px;line-height:1.6}.config{display:grid;grid-template-columns:2fr 1fr 100px auto auto;gap:12px;align-items:end}.config label{font-size:11px;font-weight:700;text-transform:uppercase;color:#727272}.config input,.editor select{display:block;width:100%;margin-top:6px;background:#fff;border:1px solid #d7d5cf;padding:11px;font:13px "DM Mono",monospace}.config button,.commit{border:0;background:#1f2328;color:#fff;padding:12px 16px;font-weight:700;cursor:pointer}.config .secondary{background:#777}.status{font-size:13px}.editor{border:1px solid #d7d5cf;background:#fff}.editor-bar{display:flex;justify-content:space-between;padding:12px;border-bottom:1px solid #d7d5cf}.editor-bar label{font-size:12px;cursor:pointer}.editor-bar input{display:none}.editor textarea{width:100%;height:540px;border:0;resize:vertical;padding:20px;font:13px/1.6 "DM Mono",monospace;outline:0}.commit{margin:12px;background:#ff5a36}@media(max-width:700px){.admin-page{width:calc(100% - 32px);padding-top:35px}.config{grid-template-columns:1fr}.editor textarea{height:400px}}</style>
